---
title: 'Math475 Homework4 '
author: 'Muzhou liu '
date: "November 09, 2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: \usepackage{amsthm}
---


```{r setup, echo=FALSE, include=FALSE}
# set global chunk options: images will be 7x5 inches
knitr::opts_chunk$set(fig.width=7, fig.height=5)
options(digits = 8)
library(tidyverse)
library(GGally)
library(latex2exp)
library(rmutil)
library(tolerance)
```

# problem 5.7


```{r}
m = 10000
u = runif(m/2)
u_anti = 1 - u

g_anti = ( exp(u) + exp(u_anti) )/2

E_anti = mean( g_anti )

var_anti = var( g_anti )/(m/2)

u_simp = runif(m)
E_simp = mean( exp(u_simp) )
var_simp = var( exp(u_simp) )/m
perc_reduc = 100*(var_simp - var_anti)/var_simp
###output
c(E_simp, E_anti)
c(var_simp, var_anti, perc_reduc)


```


```{r}
g4 <- function(x){ x^2/sqrt(2*pi) * exp(-x^2/2)
}
qPareto1 <- function(u,b=1) {return( 1/(1-u)^(1/b) ) }
rPareto1 <- function(m, b=1) {qPareto1(runif(m),b) }
x1 <- rPareto1(10000,0.5) 
gf1 = g4(x1)/((0.5/x1^1.5)) 
mean(gf1)
var(gf1)
q_my <- function(u) { log(u/1.34986, base = 0.740818)
}
r_my <- function(m){ q_my(runif(m))} 
x2 <- r_my(10000)
gf2 <- g4(x2)/(0.3*exp(-0.3*x2+0.3))
mean(gf2)
var(gf2)

x2 <- r2exp(10000,10/3,1)

gf2 <- g4(x2)/d2exp(x2,10/3,1)


mean(gf2)

var(gf2)

integrate(g4,1,Inf)

```
The mean we got from the two importance sampling are close the the true one. 

Actually $\phi_2(x)$ has a slightly smaller variance that cannot tell using the plot in problem 5.13. 

# Problem 5


## a)
```{r}

root1 <- 1/5
root2 <- 2/5 

slope1 <- dbeta(root1,3,5)/root1
slope2 <- dbeta(root2,3,5) /(root2-1)

convex_x <-  -slope2/(slope1-slope2)
convex_y <- slope1*convex_x

area <- convex_y/2

```


## b)

```{r}
invcdf <- function(x){
  return(ifelse(x < convex_x, 
         sqrt(x*area*2*(1/slope1)),
         1-sqrt((1-x)*2*area*(-1/slope2))))
}

triangle_pdf <- function(x){
  return(ifelse(x < convex_x, slope1*x/area , (-slope2 +slope2*x)/area ))
} 

accept_rej_samp <- function(n) {
  
  n_accept  <- 0 
  counter <- 0 
  X <- rep(0,n)
  
  while(n_accept < n ) {
    counter <- counter + 1
    v=runif(1)
		x_prime=invcdf(v)
    	if(runif(1) <= dbeta(x_prime,3,5)/(area*triangle_pdf(x_prime))) {
      		n_accept <- n_accept + 1
      		X[n_accept] <- x_prime
    	}
		}
  return(list(sample= X, rate = n/counter))
}


```

## c)
```{r}
result <- accept_rej_samp(10000)

print(paste('rate is' , result$rate, ' 1/c is ', 1/area ))

```

## d)
```{r}
data.frame(k=result$sample) %>% 
  ggplot(aes(k,y=..density..)) + 
  geom_histogram(color = 'black', fill = 'white') + 
  geom_density(data =data.frame( true =  qbeta(seq(0, 1, length=10000),3,5)), 
               aes(true),alpha=.2, fill="#FF6666")


qqplot( rbeta(10000,3,5),result$sample)
qqline(rbeta(10000,3,5),datax = TRUE, distribution = function(x){qbeta(x,3,5)}, col= 'red')
  
```

Both the density plot and Q-Q plot shows that our sample is from Beta(3,5)
